import chromium from '@sparticuz/chromium'
import puppeteer from 'puppeteer-core'

export const config = { maxDuration: 120 }
const PROJECT_URL='https://eyngapizkxsernywdyfv.supabase.co',KEY='sb_publishable_Iyht5_rKaUOeHBz9sh0xRQ_eX6r8tfc',STATE=`${PROJECT_URL}/functions/v1/dealer-intel-api`
function ok(v){if(!/^[A-HJ-NPR-Z0-9]{17}$/.test(v))return false;const m={A:1,B:2,C:3,D:4,E:5,F:6,G:7,H:8,J:1,K:2,L:3,M:4,N:5,P:7,R:9,S:2,T:3,U:4,V:5,W:6,X:7,Y:8,Z:9},w=[8,7,6,5,4,3,2,10,0,9,8,7,6,5,4,3,2];let s=0;for(let i=0;i<17;i++){const c=v[i],n=/\d/.test(c)?+c:m[c];if(n==null)return false;s+=n*w[i]}return v[8]===(s%11===10?'X':String(s%11))}
const vins=t=>[...new Set((t.toUpperCase().match(/[A-HJ-NPR-Z0-9]{17}/g)||[]).filter(ok))].sort(),host=u=>new URL(u).hostname.toLowerCase().replace(/^www\./,''),same=(a,b)=>host(a)===host(b)
function platform(t){const s=t.toLowerCase();if(s.includes('dealerinspire')||s.includes('/llm/inventory'))return'DEALERINSPIRE';if(s.includes('dealeron.com')||s.includes('dealeron.js')||s.includes('/api/vhcliaa/'))return'DEALERON';if(s.includes('dealer.com')||s.includes('ddc-'))return'DEALER_DOT_COM';if(s.includes('dealerfire'))return'DEALERFIRE';return'GENERIC_BROWSER'}
function total(t){for(const p of[/showing\s+\d+\s*(?:-|–|to)\s*\d+\s+of\s+(\d+)/i,/(?:totalCount|totalVehicleCount|inventoryCount)[\"']?\s*[:=]\s*[\"']?(\d+)/i,/data-(?:total|count|total-count|vehicle-count)=[\"'](\d+)[\"']/i,/([1-9]\d{0,3})\s+(?:new\s+)?vehicles?\s+(?:found|available|in stock)/i,/([1-9]\d{0,3})\s+(?:results?|matches?)\b/i]){const m=t.match(p);if(m)return +m[1]}return null}
function next(t,u){const m=t.match(/<link[^>]+rel=[\"']next[\"'][^>]+href=[\"']([^\"']+)[\"']/i)||t.match(/<a[^>]+(?:rel=[\"']next[\"']|aria-label=[\"'](?:next|next page)[\"'])[^>]+href=[\"']([^\"']+)[\"']/i);if(!m?.[1])return null;try{const n=new URL(m[1],u).toString();return same(n,u)?n:null}catch{return null}}
async function capture(page,u){await page.goto(u,{waitUntil:'domcontentloaded',timeout:40000});await new Promise(r=>setTimeout(r,900));for(let i=0;i<8;i++){await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));await new Promise(r=>setTimeout(r,350));const clicked=await page.evaluate(()=>{const e=[...document.querySelectorAll('button,a')].find(x=>/^(load more|show more|view more|more vehicles|see more)$/i.test((x.textContent||'').trim())&&!x.disabled);if(e){e.click();return true}return false}).catch(()=>false);if(!clicked&&i>2)break}return page.evaluate(()=>({html:document.documentElement.outerHTML,text:document.body?.innerText||'',url:location.href}))}
async function scan(page,url,website){const seen=new Set(),all=new Set(),pages=[];let u=url,reported=null,p='GENERIC_BROWSER',exhausted=false;for(let i=0;i<50;i++){if(seen.has(u)){exhausted=true;break}seen.add(u);const x=await capture(page,u);if(!same(x.url,website))throw Error('Off-host redirect');p=platform(x.html);const t=x.text+'\n'+x.html,vs=vins(t),tt=total(t);vs.forEach(v=>all.add(v));if(tt!=null)reported=reported==null?tt:Math.max(reported,tt);pages.push({url:x.url,vin_count:vs.length});const n=next(x.html,x.url);if(!n){exhausted=true;break}u=n}const list=[...all].sort();let coverage='INCOMPLETE',reason='Full new-inventory coverage not proven.';if(p==='DEALERON'&&exhausted&&list.length){coverage='COMPLETE';reason=`DealerOn browser pagination exhausted after ${pages.length} page(s).`}else if(reported!=null&&list.length===reported&&exhausted){coverage='COMPLETE';reason=`Browser VIN count ${list.length} reconciled exactly to reported total ${reported}.`}else if(reported!=null)reason=`Observed ${list.length} validated VINs but platform reports ${reported}; refusing COMPLETE.`;return{final_url:pages[0]?.url||url,platform:p,pages_scanned:pages.length,pagination_exhausted:exhausted,reported_total:reported,coverage_status:coverage,completeness_reason:reason,vehicles:list.map(vin=>({vin})),page_evidence:pages}}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST only'});if(req.headers.apikey!==KEY)return res.status(401).json({error:'Unauthorized application key.'});const id=String(req.body?.dealerId||'');if(!/^\d{1,12}$/.test(id))return res.status(400).json({error:'Invalid dealer id.'});let browser;try{const sr=await fetch(STATE,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({operation:'state'})}),st=await sr.json(),d=st.dealers?.find(x=>x.dealer_id===id);if(!d)return res.status(404).json({error:'Dealer not found.'});browser=await puppeteer.launch({args:chromium.args,defaultViewport:{width:1440,height:1100},executablePath:await chromium.executablePath(),headless:true});const page=await browser.newPage(),base=new URL(d.website),c=['/llm/inventory/?type=new','/searchnew.aspx','/new-inventory/index.htm','/new-vehicles/','/new-inventory/','/inventory/new'].map(p=>new URL(p,base).toString());let best=null;for(const u of c){try{const x=await scan(page,u,d.website);if(!best||x.vehicles.length>best.vehicles.length||x.coverage_status==='COMPLETE')best=x;if(x.coverage_status==='COMPLETE')break}catch{}}if(!best)throw Error('No browser inventory candidate produced usable evidence.');return res.status(200).json({dealer_id:id,dealer_name:d.dealer_name,dealer_website:d.website,...best})}catch(e){return res.status(500).json({error:e.message})}finally{if(browser)await browser.close().catch(()=>{})}}
